// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv17UA6EYGdCDEAMfpqdRJvODQBUTtFzA',
    appId: '1:137431639075:web:f766df46f3aeee7f44bd96',
    messagingSenderId: '137431639075',
    projectId: 'mytestingproject123-ec8b7',
    authDomain: 'mytestingproject123-ec8b7.firebaseapp.com',
    databaseURL: 'https://mytestingproject123-ec8b7-default-rtdb.firebaseio.com',
    storageBucket: 'mytestingproject123-ec8b7.firebasestorage.app',
    measurementId: 'G-HHR47YG76B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJAEHF2Hs4mD7TcvWxGOSE0xWr8Mr4m_A',
    appId: '1:137431639075:android:f648e9d8e72f6db944bd96',
    messagingSenderId: '137431639075',
    projectId: 'mytestingproject123-ec8b7',
    authDomain: 'mytestingproject123-ec8b7.firebaseapp.com',
    databaseURL: 'https://mytestingproject123-ec8b7-default-rtdb.firebaseio.com',
    storageBucket: 'mytestingproject123-ec8b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAebH-zy3pnGBnfTF2fUz10twmggv9xnSs',
    appId: '1:137431639075:ios:d90b756a1506a6c644bd96',
    messagingSenderId: '137431639075',
    projectId: 'mytestingproject123-ec8b7',
    storageBucket: 'mytestingproject123-ec8b7.firebasestorage.app',
    iosBundleId: 'com.example.widget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAebH-zy3pnGBnfTF2fUz10twmggv9xnSs',
    appId: '1:137431639075:ios:d90b756a1506a6c644bd96',
    messagingSenderId: '137431639075',
    projectId: 'mytestingproject123-ec8b7',
    storageBucket: 'mytestingproject123-ec8b7.firebasestorage.app',
    iosBundleId: 'com.example.widget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv17UA6EYGdCDEAMfpqdRJvODQBUTtFzA',
    appId: '1:137431639075:web:0a9454eae0714a1744bd96',
    messagingSenderId: '137431639075',
    projectId: 'mytestingproject123-ec8b7',
    authDomain: 'mytestingproject123-ec8b7.firebaseapp.com',
    storageBucket: 'mytestingproject123-ec8b7.firebasestorage.app',
    measurementId: 'G-SBBP6R81XG',
  );
}
